using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class posion : MonoBehaviour
{
    public Transform mano;
    private void OnTriggerStay(Collider other)
    {
        if (gameObject.transform.Find("agarre"))
        {
            // Obtener el Transform del hijo "agarre"
            Transform agarre = gameObject.transform.Find("agarre");

            if (agarre != null)
            {
                // Mueve el objeto padre a la posici칩n de "mano" m치s la posici칩n relativa de "agarre"
                gameObject.transform.position = mano.transform.position + (gameObject.transform.position-agarre.position);

                // Alinea la rotaci칩n con la de "mano"
                gameObject.transform.rotation = mano.transform.rotation;
            }
        }
    }
}
